import type { TimelineEntry } from '@/components/ui/timeline-component';

export const PROJECTS: TimelineEntry[] = [
  {
    id: 'proj-1',
    title: 'Portfolio Website',
    logo: 'https://assets.chanhdai.com/images/companies/quaric.svg',
    isCurrent: false,
    period: '2024',
    children: [
      {
        id: 'proj-1-1',
        title: 'My Personal Portfolio site',
        subtitle: 'Side Project',
        period: '2024',
        icon: 'code',
        description: `Built a personal portfolio with Next.js and Tailwind CSS to showcase my work and skills.`,
        skills: ['Next.js', 'React', 'TailwindCSS', 'Vercel'],
      },
    ],
  },
  {
    id: 'proj-2',
    title: 'Task Manager App',
    logo: 'https://assets.chanhdai.com/images/companies/quaric.svg',
    isCurrent: false,
    period: '2023',
    children: [
      {
        id: 'proj-2-1',
        title: 'Developer',
        subtitle: 'Side Project',
        period: '2023',
        icon: 'code',
        description: `A Kanban-style task management app with drag-and-drop features.`,
        skills: ['React', 'TypeScript', 'Firebase', 'Framer Motion'],
      },
    ],
  },
  {
    id: 'proj-3',
    title: 'E-Commerce Platform',
    logo: 'https://assets.chanhdai.com/images/companies/quaric.svg',
    isCurrent: false,
    period: '2023',
    children: [
      {
        id: 'proj-3-1',
        title: 'Lead Developer',
        subtitle: 'Freelance',
        period: '2023',
        icon: 'business',
        description: `Full-stack e-commerce platform with authentication, payments, and order management.`,
        skills: ['Next.js', 'Stripe', 'Prisma', 'PostgreSQL'],
      },
    ],
  },
  {
    id: 'proj-4',
    title: 'Chat Application',
    logo: 'https://assets.chanhdai.com/images/companies/quaric.svg',
    isCurrent: false,
    period: '2022',
    children: [
      {
        id: 'proj-4-1',
        title: 'Backend Engineer',
        subtitle: 'Personal Project',
        period: '2022',
        icon: 'code',
        description: `Real-time chat app with private/group messaging and typing indicators.`,
        skills: ['Node.js', 'Socket.IO', 'MongoDB', 'Express'],
      },
    ],
  },
  {
    id: 'proj-5',
    title: 'Blog CMS',
    logo: 'https://assets.chanhdai.com/images/companies/quaric.svg',
    isCurrent: false,
    period: '2022',
    children: [
      {
        id: 'proj-5-1',
        title: 'Fullstack Developer',
        subtitle: 'Freelance',
        period: '2022',
        icon: 'code',
        description: `Markdown-powered blog with an admin dashboard for content management.`,
        skills: ['Next.js', 'Strapi', 'GraphQL'],
      },
    ],
  },
  {
    id: 'proj-6',
    title: 'Weather Dashboard',
    logo: 'https://assets.chanhdai.com/images/companies/quaric.svg',
    isCurrent: false,
    period: '2021',
    children: [
      {
        id: 'proj-6-1',
        title: 'Frontend Dev',
        subtitle: 'Hackathon Project',
        period: '2021',
        icon: 'design',
        description: `Weather app with forecasts and interactive charts using public APIs.`,
        skills: ['React', 'Chart.js', 'OpenWeather API'],
      },
    ],
  },
  {
    id: 'proj-7',
    title: 'Expense Tracker',
    logo: 'https://assets.chanhdai.com/images/companies/quaric.svg',
    isCurrent: false,
    period: '2021',
    children: [
      {
        id: 'proj-7-1',
        title: 'Frontend Dev',
        subtitle: 'Personal Project',
        period: '2021',
        icon: 'code',
        description: `App to track expenses and visualize spending habits with charts.`,
        skills: ['Vue', 'Firebase', 'TailwindCSS'],
      },
    ],
  },
  {
    id: 'proj-8',
    title: 'Fitness Tracker',
    logo: 'https://assets.chanhdai.com/images/companies/quaric.svg',
    isCurrent: false,
    period: '2020',
    children: [
      {
        id: 'proj-8-1',
        title: 'Mobile Dev',
        subtitle: 'Personal Project',
        period: '2020',
        icon: 'code',
        description: `Mobile-friendly app to log workouts, nutrition, and progress.`,
        skills: ['React Native', 'Expo', 'SQLite'],
      },
    ],
  },
  {
    id: 'proj-9',
    title: 'Recipe Finder',
    logo: 'https://assets.chanhdai.com/images/companies/quaric.svg',
    isCurrent: false,
    period: '2020',
    children: [
      {
        id: 'proj-9-1',
        title: 'Developer',
        subtitle: 'Side Project',
        period: '2020',
        icon: 'code',
        description: `Search and save recipes using a public recipe API with bookmarking features.`,
        skills: ['Next.js', 'Redux', 'Spoonacular API'],
      },
    ],
  },
  {
    id: 'proj-10',
    title: 'Stock Market Analyzer',
    logo: 'https://assets.chanhdai.com/images/companies/quaric.svg',
    isCurrent: false,
    period: '2019',
    children: [
      {
        id: 'proj-10-1',
        title: 'Data Engineer',
        subtitle: 'Research Project',
        period: '2019',
        icon: 'code',
        description: `Tool to analyze stock market trends with data visualization and watchlists.`,
        skills: ['Python', 'Pandas', 'Plotly', 'FastAPI'],
      },
    ],
  },
];
